### PR TITLE
Added ability to change axis arbitrarily

### PR DESCRIPTION
**Pull request by JemarJones**
also a couple useful things like toggling. I'm submitting to this branch as it's the best IMO and i'm not sure  if the original dev is taking pull requests at all? But anyway ive added a couple functions for changing the axis after a card has already been created. This should eventually be extended to other properties but i've just worked on the property i personally needed.

### CODE REVIEW

**Comment by Download** [comment]
Hi, the feature that you suggests sounds useful.

Indeed I don't know whether the other flip fork is still maintained, so I'm willing to merge in your changes so we can create a new fork with everything in it.

I added some notes to the commits. Can you adress those?

**Comment by JemarJones** [comment]
1. Would i need to make it so that that action parameter is needed when calling the function with its previous functionality? My only concern there would be backwards compatibility with the previous API. 
2. Looks good, could you link me to anything explaining why that works? For my own knowledge.
3. Sure no problem.

**Comment by JemarJones** [comment]
Also the more i think about it the 2nd function i had added "setAndFlip" doesn't really seem to belong, so i think i'll remove that.

**Comment by Download** [comment]
**1.** Yes, backward compatibility is important :)  

If you look at line 36 of [src/flip.js](https://github.com/Download/flip/blob/master/src/flip.js) it has this code:

``` javascript
if (options !== undefined && typeof(options) == "boolean") { // Force flip the DOM
```

From the docs of flip, combined with this code, I come to the conclusion that there are basically two ways of calling flip:
1. With a boolean
2. With an (optional) options object

So as of yet there is no way of calling flip with a string as the first parameter. So my suggestion would be to add that. I see you already added the check for a string parameter. Basically you are already doing it a bit. I would just move the code for `setAxis` to a separate function, like it was already done for `unflip`, and call that from within the flip function if the string is `'setAxis'`.

**2.** This article from John Resig (author of jQuery) might be a good start: [How Javascript timers work](http://ejohn.org/blog/how-javascript-timers-work/). I think they call the 'unpredictable order' problem 'Zalgo'... As in 'releasing Zalgo'... This article deals with it specifically: [Designing APIs for Asynchrony](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony)

Basically there is only one thread in Javascript. So the code in a callback you assign to some DOM event is always run only after all other code in the current function has finished. So only after the `alert('Hello');` statement has finished. `setTimeout` works in the same way. The code is added to a list of event listeners that will be called (as closely as possible) after the specified timeout in milliseconds has passed, but never before the current function has executed. When you call the callback function directly however, it's executed immediately. The rule of thumb is that if, within a function, a certain callback function is _sometimes_ called async, then it's best to make sure that it's _always_ called async to prevent this unpredictable order problem.

**3.** Thanks!

> Also the more i think about it the 2nd function i had added "setAndFlip" doesn't really seem to belong, so i think i'll remove that.

I agree. I do however like your `toggle` function. If you implement **1.**, then why not add that as well? If you make `setAxis` return `this` to allow for chaining, than the alternative for your `setAndFlip` function becomes:

``` javascript
$('#card').flip('setAxis', 'vertical').flip('toggle');
```

**Comment by Download** [comment]
I just realized that although my answer to your first question is long, it's not that clear  :)  So just to make it simple:

No, I don't think we should require the parameter for the old ways of calling flip. We should remain backward compatible. So after your change these should be the ways of calling flip:

``` javascript
$('#card').flip();  // make flippable with default options
$('#card').flip(options);  // make flippable with custom options
$('#card').flip(true);  // show the back of the card
$('#card').flip(false);  // show the front of the card
$('#card').flip('setAxis', axis);  // NEW: set the flip axis
$('#card').flip('toggle');  // NEW: toggle the card front/back
```

**Comment by JemarJones** [comment]
1. That looks great and wasn't unclear the first time :). I'm just now thinking that maybe it'd be best to attempt to future proof it a little bit and set it up like `$('#card').flip('set', options);` and just for now only support the axis option. So in the future if its appropriate we can just build on that and still have a nice api. 
2. Thanks alot!
3. That's a really good idea, to do that i could just return the `this` right after the callback right?

Also sorry about the prolonged response times, a little busy with work.

Edit: Actually.. taking the idea in **1.** to its extreme/natural progression, would the first 'set' parameter even be necessary? we could just reuse the `$('#card').flip(options);` call and either detect that the objects already been initiated or maybe figure out how to better merge it into one function? Maybe i'm thinking a little crazy here but let me know what you think.

**Comment by Download** [comment]
No worry about the response times, I have the same. :)

**1.** Well I have to say I think your idea is quite good actually. So one would just be able to call flip like this:

``` javascript
$('#card').flip({'axis': 'x'});
```

I see that two of the settings are stored on the DOM element. They seem candidates for your idea:
- `reverse`
- `axis`

**2.** Welcome!

**3.** Yes, just return `this`. It is [recommended](https://learn.jquery.com/plugins/basic-plugin-creation/#chaining) by jQuery for any methods that don't need to return a value to return `this`.

Edit:  I see that the `flip` function itself already does chaining. So we could end up with:

``` javascript
$('#card').flip({'axis': 'x'}).flip('toggle');
```

Seems very nice to me!

**Comment by JemarJones** [comment]
**1.** Yea i had tried to figure out how to implement it for reverse earlier but couldn't quite figure it out, but it should definitely be part of this. 

**3.**  Okay looks good.

## 

This is looking good and i think we're very close. I'm just stuck on a couple of things. 
**a)** It seems like if we're  going to have `$('#card').flip({'axis': 'x'}, callback)` be an option sometimes, it should be an option every time. But i'm not sure at which point the callback should be called in regards to the original functionality?

**b)** Furthermore, having to callback and return from within the `.each` (which i shouldve included in my original function) confuses me a little bit. I'm no longer sure where the appropriate point to callback is? And for the chaining with the toggle chaining to work correctly, i need to return once the animation is done (wherever i callback).

Not sure how to go about all that.

**Comment by JemarJones** [comment]
So i've now got a decent solution for calling back from within the .each. I'm still not sure how to only `return` once the setup is complete. I now know that i can actually return the `this.each` directly but i need to only return once we're ready to callback.  I've also still not worked out **a)**.

**Comment by Download** [comment]
Does `setAxis` cause an animation?
I would think it would only have an effect the next time the element is flipped?
Is it a side-effect of setting the transform? E.g. the code below `//This sets up the first flip in the new direction automatically`?
If so, can you maybe solve it by (temporarily) turning off transition?

A working example would help, so I could have a look at the working code and see what the issue is. Doesn't have to be the new stuff, can also be the old stuff... Both are fine by me

**Comment by JemarJones** [comment]
Yeup its the transform that causes an animation. Its needed to setup the card on the other side to be flipped. Or atleast that's what i believe it's doing based on the same technique used in the original function. Removing it causes the card coming from the other side to flip in the wrong direction on the initial flip. I'm now pretty sure that the desired `$('#card').flip({'axis': 'x'}).flip('toggle');` isn't really possible because of how async code works and that we'll have to settle for the 

``` javascript
    $('.card').flip({axis: 'x'},function(){ 
          $('.card').flip("toggle");
    });
```

method.

If we're okay with that then the only thing currently not working is _a)_. When an element is initiated there seems to be several animations that take place so the method i use for setaxis:

``` javascript
      if (callback !== undefined){
       $(this).on("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd", function(){
        callback.call(this);
        $(this).off("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd");
       });
      }
```

doesn't quite work. It detects the end of an animation, but there may more than one animation we need to wait to end. Currently if you take a look at line 50 and 144 in flip.js i'm just calling back directly, which doesn't rely on when the animations finish at all and is unstable. You can see everything i'm talking about in https://jsfiddle.net/04pq2uwp/13/ :). Once that's figured out we should be good.

**Comment by JemarJones** [comment]
Also sorry about the diff in that last commit, something must've happened to the indentation or something. Looks like i changed a ton of things that haven't been touched at all as far as i can tell.

If you go to this url ('?w=1' added to the end) https://github.com/JemarJones/flip/commit/12e5dbdf151f5f6f145092706a3535fc6e0b628c?w=1 you can see a more accurate diff.

**Comment by Download** [comment]
Merged and part of release v1.0.6.

As there's now at least as much of your code in there as there is of mine I think it's only fair you get push access. So I made you a collaborator of this project. Congratulations!

**Comment by JemarJones** [comment]
Awesome, thanks :)

**Comment by Download** [comment]
:+1:

**Comment by Download** [comment]
I realized you were still mentioning some open issues, but I think sometimes it's best to just get in what you've already got and then work from there. Since you are a collaborator now you can just amend it whenever you feel the need.

If you changed something and feel it should be releases, just let me know and I will create a new release (or you can do it yourself if you know how it's done).

**Comment by JemarJones** [comment]
Okay sounds good to me. I'll move those changes from that other pull request over to a branch here later on and address your comments.

**Comment by Download** [comment]
Great, thank you!

**Comment by Download** [comment]
I added examples for `flip('toggle')` and `flip({axis: 'x'})` to the [project website](https://download.github.io/flip/)

**Comment by JemarJones** [comment]
Should we perhaps rename/rebrand this project to something like 'flip2' so as not to confuse it with the original? We'd still give full credit of course.

**Comment by Download** [comment]
Yes I have been playing with the same thought  :)

**Pull request merged**
